src/ethereum/mod.rs

Mock mode can be activated either via CLI param `-m true` or now an env var `SIGNUP_SEQUENCER_MOCK`

Add env var for mocking eth connection

---

.github/workflows/build-test-deploy.yml
deploy/templates/cors.yaml
deploy/templates/ingress.yaml
deploy/values.yaml

I've got a request to configure CORS for the API.
I use Traefik middleware to inject cors headers. The solution was tested on stage:
```
curl -i --location --request POST 'https://signup.stage-crypto.worldcoin.dev/insertIdentity' \
--header 'Content-Type: application/json' \
--data-raw '[0, "0x0000000000000000000000000000000000000000000000000000000000000000"]'
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
curl -i --location --request OPTION https://signup.stage-crypto.worldcoin.dev/
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Origin: *
```
The OPTIONS request on root context should return an empty body 204 response instead of 500. I think this should be handled on the application level.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

B-522 feat(traefik): Add CORS configuration as Traefik middleware

---

deploy/templates/cors.yaml

we can’t do the parsing correctly in the frontend
if you try to do a request from the browser,
```
Access to fetch at 'https://signup.stage-crypto.worldcoin.dev/insertIdentity' from origin 'http://localhost:54702/' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.
```
We add `content-type` for Access-Control-Allow-Headers list
Checked on stage:

Add content-type to allowed cors headers

---

src/app.rs

There is a race condition when multiple tree insertions happen at the same time due to waiting on the transaction to be mined.
Hot fix in this PR: 
- Add mutex for the whole scope of the function. However, this will now block insertions until the transaction is mined.
- We can't reuse the mutex on the whole tree (`self.merkle_tree.write().await`), because this also blocks read queries in the api for the inclusion proof. 
**TODO:** Remove the transaction waiting from the mutex, so we can submit and wait for multiple tx in parallel.

Fix race condition in `insert_identity`

---

.github/workflows/build-test-deploy.yml
src/ethereum/mod.rs

Submitting a transaction to polygon mainnet currently fails with `transaction underpriced`. This is because `max_fee_per_gas` is set in correctly, such that `max_fee_per_gas` -  `max_priority_fee_per_gas` < `base_fee`. 
Geth will [reject such transactions instantly](https://github.com/ethereum/go-ethereum/issues/24079).
This migth be bug in ether-rs failing to parse the current basefee returned from the rpc, but needs futher investigation. 
Switching legacy fixes it for now.
On mumbai this does not occur because there is no min fee enforced, Polygon mainnet enforces >=30gwei min basefee fee for spam protection.

disable eip1559 on mainnet

---

.github/workflows/build-test-deploy.yml
src/app.rs
src/ethereum/mod.rs

While syncing, we are exceeding the data limit of events:
```
Error: 
0: (code: -32602, message: Log response size exceeded. You can make eth_getLogs requests with up to a 2K block range and no limit on the response size, or you can request any block range with a cap of 10K logs in the response. Based on your parameters and the response size limit, this block range should work: [0x0, 0x1afef94], data: None)
Location:
/src/src/ethereum/mod.rs:165
```
Iterate over block ranges.

sync events with block range

---

deploy/templates/statefulset.yaml

Container name should match with `ad.datadoghq.com/` annotations to work properly.

fix: rename container name to fit datadog and prometheus instance configuration [B-696]

---

.github/workflows/build-test-deploy.yml

We have to choose the previous version of snyk because the latest release doesn't contain binary files.

fix: choosed previous version of snyk

---

schemas/openapi.yaml
src/app.rs
src/server.rs
tests/integration-tests.rs

The specs were missing. This updates them, though without validation yet.

Provide OpenAPI specs and differentiate response codes in inclusionProof

---

src/contracts/mod.rs

Apparently printing an eyre report can cause the app to freeze. This is a band aid, and needs a far deeper investigation.

Don't wrap tx error in eyre

---

schemas/openapi.yaml
src/app.rs
tests/integration-tests.rs

Accidentally introduced an API incompatibility before, and it passed tests because they used the same serializer as the server. Fixed the API _and_ the tests to not have this problem in the future.

Flatten proof response

---

.github/workflows/build-test-deploy.yml
.gitignore
Cargo.lock
Cargo.toml
src/app.rs
src/identity_committer.rs
src/lib.rs
src/timed_read_progress_lock.rs
src/utils.rs

If the future supplied to `tokio::spawn` returns an error or panics this is not noticed until the task handle is joined. This PR makes it such that the fault is loggedn and the whole process aborts immediately.

Catch panics and errors in background threats

---

deploy/templates/statefulset.yaml

```
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/arch]: deprecated since v1.14; use "kubernetes.io/arch" instead
```
This label has been deprecated. Use kubernetes.io/arch instead.

Update deprecated deployment label

---

Cargo.lock
Cargo.toml
src/app.rs
src/contracts/mod.rs
src/database.rs
src/ethereum/mod.rs
src/identity_committer.rs
src/lib.rs
src/main.rs
src/server.rs
src/utils.rs
tests/integration-tests.rs

Following up on https://github.com/worldcoin/signup-sequencer/pull/295, we had another instance where logging `eyre::Report` with `tracing` and `otlp` enabled completely hanged the app (and prevented it from restarting successfully).
It looks like `anyhow` doesn't have this problem. We can continue investigating what exactly causes OTLP and eyre to misbehave so badly, but for now this should fix the production.

replace eyre with anyhow

---

src/server.rs

It was commented out in https://github.com/worldcoin/signup-sequencer/pull/307 by accident while testing whether `otlp` was the culprit.
In my testing, `trace_from_headers`, `anyhow`, `oltp` together don't cause any issues.
/ cc @recmo

re-enable trace_from_headers function

---

src/app.rs
src/database/mod.rs
src/ethereum/mod.rs
src/ethereum_subscriber.rs

This does a few things:
* increase confirmation delay to 35 blocks to have fewer failures on polygon
* stop logging errors for leaves that we already know are empty or duplicated. only log new errors.
* increase cache resiliency by multi-stage recovery:
* start with the full cache loaded; on root mismatch:
* remove the most recent 1000 cached blocks; on root mismatch:
* remove the entire cache; on root mismatch:
* restart app.
Example from my local sequencer:
* root mismatch 100 blocks from the head:
* root mismatch more than 1000 blocks from the head:

Better cache invalidation, longer confirmation delay

---

.github/workflows/build-test-deploy.yml

Our CI died because of upstream changes in other actions. Freezing to the non-broken version.

Freeze docker buildx version

---

.github/workflows/build-test-deploy.yml

This doesn't work now that we have a feature that switches between the legacy and batching contracts.

Avoid building and testing with all features on CI

---

Cargo.toml
build.rs
deploy/Chart.yaml
src/app.rs
src/contracts/batching/abi.rs
src/contracts/batching/mod.rs
src/contracts/legacy/abi.rs
src/contracts/legacy/mod.rs
src/contracts/mod.rs
src/ethereum_subscriber.rs
src/identity_committer.rs
tests/integration-tests.rs

This PR refactors how the existing legacy contract is handled by introducing a trait to unify behaviour between the two contracts. This is in preparation for introducing the batching contract to the codebase with the swap between the two controlled by a cargo feature.
There are no functional changes in this PR, but it does make some renames around the codebase to make things clearer now that "semaphore" is not the only contract. To that end, it intentionally does not test what little integration of the batching prover there is.

Initial Refactoring for Batching Integration

---

Cargo.lock
Cargo.toml
src/app.rs
src/contracts/batching/mod.rs
src/contracts/mod.rs
src/lib.rs
src/prover/identity.rs
src/prover/mod.rs
src/prover/proof.rs
tests/integration-tests.rs

This commit does some initial integration with the batch prover by connecting to `semaphore-mtb` and requesting proofs from it. It does not yet use these proofs in the batch prover.

Connect to and work with the prover service

---

deploy/templates/statefulset.yaml

We need to set an explicit name for the service because, without this env datadog tries to guess it and now uses its chart name. It was ok when we had only one deployment. Now, we have more than one, and we should be able to split those logs/metrics with the service field.

fix: set DD_SERVICE env

---

Cargo.toml
src/contracts/mod.rs
src/ethereum/mod.rs
src/ethereum/write/mod.rs
src/ethereum/write_dev/mod.rs
src/ethereum/write_oz/mod.rs
src/ethereum/write_oz/openzeppelin.rs
src/identity_committer.rs
src/prover/batch_insertion/mod.rs

It can take a long time to confirm a transaction on the chain. In that time we could have been already preparing and proving the next batch.
"Sending" an identities commitment transactions is split into 3 phases:
1. Preparing the proof - prepares proof data and sends it to the prover
2. Sending the transaction - only sends the transaction to the RPC (or OZ Defender Relay)
3. Mining the transaction - awaiting for the transaction to be finalized on chain
The process is synchronized with a channel in such a way that we can already start preparing the next proof while the previous transaction is still unconfirmed.
1. Added `total_proving_time` and `prover_proving_time` metrics
1. [x] ~Tests~ - will work on testing later, codebase needs a bit more work to enable that
2. [ ] Display added …

Poll oz transactions

---

rust-toolchain.toml
src/app.rs
src/database/mod.rs
src/ethereum/mod.rs
src/ethereum/read/mod.rs
src/ethereum/read/transport.rs
src/ethereum/write/mod.rs
src/ethereum/write_dev/estimator.rs
src/ethereum/write_dev/mod.rs
src/ethereum/write_oz/mod.rs
src/identity_committer.rs
src/lib.rs
src/main.rs
src/prover/batch_insertion/mod.rs
src/server.rs

Hey, I noticed with have a lot of `#[allow`  or `#![allow` attributes sprinkled around the codebase:
```
Non-clippy:
#![allow(unused_variables, dead_code)]
#[allow(dead_code)]
#[allow(unreachable_code)]
#[allow(unused_imports)]
#[allow(dead_code)]
#[allow(unreachable_patterns)]
#[allow(deprecated)]
#[allow(dead_code)]
#[allow(dead_code)]
Correctness:
#[allow(clippy::eq_op)]
Complexity:
#![allow(clippy::extra_unused_lifetimes)]
Style:
#[allow(clippy::disallowed_methods)]
#[allow(clippy::disallowed_methods)]
Perf:
#[allow(clippy::large_enum_variant)]
#[allow(clippy::large_enum_variant)]
Pedantic:
#![allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
#![allow(clippy::cast_precision_loss)]
#[allow(clippy::semicolon_if_nothing_returned)]
#[allow(clippy::enum_glob_use)] …
```

Drop pedantic and nursery lints

---

.github/workflows/phone-build-test-deploy.yml

It was copied by mistake from the staging deploy job.

fix: name of production job to deploy app from phone/main

---

Cargo.lock
Cargo.toml
src/identity_tree.rs
src/utils.rs

`replace_with` should have actually been `unsafe`. But there already exists `take_mut::take` which does exactly what we want while also upholding the safety invariant regarding panics

Replace `replace_with` with `take_mut::take` 

---

.github/workflows/build-test-deploy.yml

1. Fixing the cache step for the build jobs, there was a permission error due to building in a container and cache was never saved
2. Switching to direct `actions/cache` usage to control cache key and improve hit rate
3. Bumping aws-actions/configure-aws-credentials to v2
```
Caused by:
failed to initialize index git repository (in "/home/runner/.cargo/registry/index/github.com-1ecc6299db9ec823")
Caused by:
failed to create locked file '/home/runner/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/config.lock': Permission denied; class=Os (2)
```

Fixing and improving caching in Github Actions workflow

---

crates/oz-api/src/data/transactions/mod.rs
src/ethereum/mod.rs
src/ethereum/write_oz/mod.rs
src/ethereum/write_oz/openzeppelin.rs

Now we validate that transactions have not been reverted before deciding to mark them as mined

Validate that transaction has not been reverted

---

schemas/openapi.yaml

The `/verifySemaphoreProof` endpoint expects that parameters are in camelCase, not snake_case as the `openapi.yaml` shows.
Update the request and response parameters in `openapi.yaml`

fix: switch from snake_case to camelCase

---

src/database/mod.rs
src/lib.rs
src/secret.rs
src/server/mod.rs
src/server/remove_auth_layer.rs

This PR introduces SecretUrl that prevents log macro with exposing username:password

Removing sensitive info from logs

---

.github/workflows/cargo-vet.yml
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

This PR adds cargo vet supply chain folder with audit imports from trusted organizations.
Current audit status is:
* 112 fully audited crates 
* 5 partially audited crates
* 576 non-audited crates
It also adds new github action workflow

Add cargo vet

---

src/database/mod.rs
src/task_monitor.rs
src/task_monitor/tasks/mine_identities.rs
src/task_monitor/tasks/process_identities.rs

In addition to the pending identities queue, we want to monitor the unprocessed identities queue. It should give us a better view of the mechanics of the workflow.

Log unprocessed identities queue

---

src/task_monitor/tasks/process_identities.rs

We've seen errors caused by OZ returning `out of gas` errors on identity registration. When that happened, the sequencer tried to send the next batch, even though the previous one errored. That's because we don't have a retry at this level. To mitigate this problem, we'll panic when this problem happens. This will ensure we retry the faulty batch.

Panic on register identities tx error

---

src/contracts/abi.rs
src/contracts/mod.rs
src/prover/mod.rs
src/task_monitor/tasks/process_identities.rs

This PR introduces logic to pad deletion proofs. The verifier and prover can only work with a given batch size, so we need to ensure that our batches match that size. We do this by padding deletion indices with tree.depth() ^ 2. The deletion prover will skip the proof for any deletion with an index greater than the max tree depth.

Deletion proof padding

---

src/task_monitor/tasks/process_identities.rs

Add more info on crash

---

schemas/database/004_identities.up.sql
src/app.rs
src/database/mod.rs
src/utils.rs
src/utils/tree_updates.rs
tests/delete_identities.rs

This PR introduces changes to the identities table to fix tree state syncing on startup. Additionally, `get_commitments_by_status` was updated to only get the `TreeUpdate` at a given leaf index with the highest `id` value.

Fix: Sync tree state / `get_commitments_by_status` 

---

schemas/database/010_latest_insertion_timestamp.sql
src/database/mod.rs
src/task_monitor/tasks/process_identities.rs

If the sequencer halts, the in-memory representation of the last time a batch was inserted is lost, therefore we need to introduce `latest_insertion_timestamp` persistence by writing it to the database.
Creates a new table called `latest_insertion_timestamp` and writes the last time a batch was inserted into the merkle tree into `insertion_timestamp`. The value is read from `process_identities` on each call and writes to it after a batch has been committed.

add insertion timestamp persistence

---

src/app.rs
tests/common/mod.rs
tests/unreduced_identity.rs

This PR adds logic to ensure the `new_commitment` is reduced when handling a payload from the `recoverIdentity` endpoint.

fix: added check for reduced identity during recovery

---

crates/postgres-docker-utils/src/lib.rs
src/database/mod.rs
tests/delete_identities.rs
tests/delete_padded_identity.rs
tests/dynamic_batch_sizes.rs
tests/insert_identity_and_proofs.rs
tests/malformed_payload.rs
tests/multi_prover.rs
tests/recover_identities.rs
tests/unavailable_prover.rs
tests/unreduced_identity.rs
tests/validate_proof_with_age.rs
tests/validate_proofs.rs

Changes the naive logic to `SocketAddr` parsing - we'll grab and use the first available socket address exposed by docker

Strengthen postgres-docker-utils

---

src/contracts/mod.rs
src/task_monitor.rs
src/task_monitor/tasks/mod.rs
src/task_monitor/tasks/monitor_txs.rs
src/task_monitor/tasks/process_identities.rs

Bring back tx monitoring

---

src/contracts/abi.rs
src/contracts/mod.rs

Change is safe since in contract constructor we're setting

Change owner to identity operator

---

src/app.rs
src/database/mod.rs
src/identity_tree/status.rs
src/server/data.rs
src/task_monitor/tasks/insert_identities.rs

This PR removes the `Failed` variant from the `UnprocessedStatus` enum. 
While this PR does not remove the `UnprocessedStatus` enum entirely, it seems that `Unprocessed` could be combined with the `ProcessedStatus` variants to have one cohesive `Status` enum ([link for reference](https://github.com/worldcoin/signup-sequencer/blob/main/src/identity_tree/status.rs#L10-L52)).

Remove `UnprocessedStatus::Failed`

---

Cargo.toml
Readme.md
crates/postgres-docker-utils/src/lib.rs
src/app.rs
src/main.rs
src/server/error.rs
src/task_monitor.rs
src/task_monitor/tasks/delete_identities.rs
src/task_monitor/tasks/finalize_identities.rs
src/task_monitor/tasks/insert_identities.rs
src/task_monitor/tasks/process_identities.rs
tests/common/mod.rs

This is a first draft of deferring tree initialization. I have some open TODOs here that I would like some feedback on.
1. different versions of `Duration` are being used in different places. Is this intended? from `chrono` and `std`. 
2. We need to delay `TaskManager::start` until after the tree initialization. It's not clear what the best way to do this is. Multiple routes we could take.
3. How should we handle the shutdown channel for `spawn_monitored_with_backoff`

Defer tree initialization PRO-498

---

src/task_monitor/tasks/delete_identities.rs

Fixes an issue where the delete_identities would loop uncontrollably

Loop without delay

---

Cargo.lock
Cargo.toml
crates/postgres-docker-utils/Cargo.toml
crates/postgres-docker-utils/src/lib.rs
src/database/mod.rs
src/shutdown.rs
supply-chain/config.toml
supply-chain/imports.lock
tests/common/mod.rs
tests/delete_identities.rs
tests/delete_padded_identity.rs
tests/dynamic_batch_sizes.rs
tests/identity_history.rs
tests/insert_identity_and_proofs.rs
tests/malformed_payload.rs
tests/more_identities_than_dense_prefix.rs
tests/multi_prover.rs
tests/recover_identities.rs
tests/tree_restore_empty.rs
tests/tree_restore_multiple_commitments.rs
tests/tree_restore_one_commitment.rs
tests/unavailable_prover.rs
tests/unreduced_identity.rs
tests/validate_proof_with_age.rs
tests/validate_proofs.rs

As discussed:
There was a bug (docker containers running after tests) in docker wrapper and to follow direction from other projects testcontainers was introduced here instead. Docker image of postgres is being used for testing. Question: which version of postgres is being used? I think it should match the version running in prod env.
There was also a bug in shutdown testing. Tests were interfering due to shutdown being called twice (once from one test and second time from the other). It was causing panic, which was causing process abort (due to rust configuration in Cargo.toml), which was causing strange/hard to understand test results (random tests being red without any special error). This test was disabled for now.
Introduced testcontainers. Disabled shutdown test.

Use testcontainers to run postgres database. Disable shutdown tests due to interfering tests (global var impl).

---

src/server/error.rs

The `signup-sequencer` currently doesn't make a distinction between identity commitments not being in the merkle tree or being invalid. This makes it harder to build logic that can differentiate those cases in the clients to this service.
In this PR we change the `IdentityCommitmentNotFound` to return a `404 - NotFound` instad of a `400 - BadRequest`.

Change id commitment not found status code from 400 to 404

---

Cargo.lock
Cargo.toml
src/database/mod.rs
supply-chain/config.toml
supply-chain/imports.lock
tests/common/mod.rs

Fix clippy warnings

---

src/server/error.rs

During implementation of the migration of Identity Delete requests between consumer DynamoDB and orb MongoDB we have experienced some issues, the part I remove in this PR is a legacy code and it introduced some confusion for us.
Removed legacy error implementation

cleanup: Remove legacy error implementation

---

src/task_monitor.rs
src/task_monitor/tasks/finalize_identities.rs
src/task_monitor/tasks/mod.rs
src/task_monitor/tasks/monitor_queue.rs

Spawn a task which reports length of the identity queue in the db.
The queue length is only reported when a new block is submitted to the blockchain which is in-frequent.
Spawn a task to report the queue length every second.

feat: report identity queue length on a timer. [PRO-588]

---

schemas/database/013_batches_and_transactions.sql
src/app.rs
src/database/mod.rs
src/database/query.rs
src/database/types.rs
src/prover/identity.rs
src/task_monitor.rs
src/task_monitor/tasks/create_batches.rs
src/task_monitor/tasks/mod.rs
src/task_monitor/tasks/process_batches.rs
tests/common/mod.rs
tests/tree_restore_multiple_commitments.rs
tests/tree_restore_one_commitment.rs
tests/tree_restore_with_root_back_to_init.rs
tests/tree_restore_with_root_back_to_middle.rs

This is a first step to introduce batches and transactions table. This is not HA solution yet - just the first step towards it.
Make small changes instead of one big.
Now processing batches is changed into 2 steps. First one is to create a batch (select identities, leaf indexes, etc.). Then the batch is saved in database. Second step is reading data from database (batch) and executes it. Proper batch execution includes storing transaction id in database.
As an alternative solution we could save in database a batch with a proves (no need to calculate it later). It will allow second step (transaction creation/execution) to not use any tree at all. It will require more memory used in database (it can be cleared from time to time as we don't need all the batches forever) but will make HA …

Added batching using DB.

---

src/task_monitor/tasks/delete_identities.rs
tests/common/mod.rs
tests/common/test_config.rs
tests/immediate_deletion.rs

Fix immediate deletion edge case

---

src/ethereum/write_provider/tx_sitter.rs

More info on send errors

---

src/database/transaction.rs
src/identity/processor.rs
src/task_monitor/tasks/insert_identities.rs

This should solve the error we were getting with serializable transactions failing, specifically when inserting identities. As well I extracted individual transactions out into their own functions for better tx composability.

Transactionalize Insert Identities Batch

---

src/app.rs
src/database/transaction.rs
src/identity/processor.rs
src/task_monitor/tasks/insert_identities.rs
src/utils/mod.rs
tests/common/mod.rs
tests/serializable_transaction.rs

This should fix the behaviour of `retry_tx!`. I've also added a test to check to make sure it's working properly. I attempted to recreate the serialization errors within our integration tests using our normal workflow but was unable to.

retry_tx fix

---

schemas/database/014_reintroduce_root_uniqueness.down.sql
schemas/database/014_reintroduce_root_uniqueness.up.sql
src/database/mod.rs

Reintroduce uniqueness check

---

.github/workflows/test.yml
.gitignore
Cargo.lock
Cargo.toml
crates/cognitoauth/Cargo.toml
rust-toolchain.toml
src/bin/tool.rs
supply-chain/config.toml
supply-chain/imports.lock

Bumps semaphore to newest with oxide branch merged.
Also adds a small CLI tool to do local proof generation and verification

Dzejkop/bump semaphore (and fix CI)

---

schemas/database/015_add_constraints_for_identities.down.sql
schemas/database/015_add_constraints_for_identities.up.sql
src/database/mod.rs
src/database/query.rs
src/database/types.rs
src/task_monitor/tasks/create_batches.rs
src/task_monitor/tasks/delete_identities.rs
src/task_monitor/tasks/insert_identities.rs

Add pre_root for identities.

---

Cargo.lock
Cargo.toml
crates/tx-sitter-client/Cargo.toml
crates/tx-sitter-client/src/lib.rs
src/bin/tool.rs
src/database/query.rs
src/database/types.rs
src/ethereum/read/mod.rs
src/prover/mod.rs
src/server/custom_middleware/api_metrics_layer.rs
src/server/custom_middleware/logging_layer.rs
src/server/custom_middleware/remove_auth_layer.rs
src/server/custom_middleware/timeout_layer.rs
src/server/mod.rs
src/shutdown.rs
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock
tests/common/mod.rs
tests/dynamic_batch_sizes.rs
tests/malformed_payload.rs
tests/unreduced_identity.rs

Updates telemetry-batteries and related deps
Cleans up some code
Adds traces to tx-sitter-monolith & prover requests

Update telemetry + traces + cleanup

---

Readme.md
schemas/database/016_remove_recovery.down.sql
schemas/database/016_remove_recovery.up.sql
schemas/openapi.yaml
src/app.rs
src/config.rs
src/contracts/mod.rs
src/database/methods.rs
src/database/mod.rs
src/database/types.rs
src/identity/processor.rs
src/identity_tree/mod.rs
src/identity_tree/status.rs
src/server/data.rs
src/task_monitor/tasks/insert_identities.rs
tests/common/mod.rs
tests/common/test_config.rs

Remove recovery related code

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml
rust-toolchain.toml
src/config.rs
src/main.rs
src/server/mod.rs
src/shutdown.rs
src/task_monitor/mod.rs
src/utils/mod.rs
supply-chain/config.toml
tests/common/mod.rs
tests/common/test_config.rs
tests/graceful_shutdown.rs

Currently we've been running with `panic="abort"` which is known to cause problems with our mmap caching system.
I've overhauled the shutdown system that we've been using to 
- make it more ergonomic
- make it more functional
- allow for graceful shutdowns through `std::process::exit`
There are now 2 ways we can shutdown long running tasks
1. - Cancel the future they're running on.
- Allows tasks to continue for a short delay period until they hit an `await` point and stall.
- This should work for 99% of cases
2. - Provide the task with it's own `Shutdown` instance and allow it some short period (30s default) to clean itself up.
Since all panics used to abort, It's possible we may have been relying on that behaviour in some places I haven't noticed. Instead now we should prefer issuing a …

Graceful Shutdown

---

src/task_monitor/tasks/create_batches.rs
src/task_monitor/tasks/delete_identities.rs
src/task_monitor/tasks/insert_identities.rs

Fix batch creation.

---

src/task_monitor/tasks/create_batches.rs
src/task_monitor/tasks/delete_identities.rs
src/task_monitor/tasks/insert_identities.rs
src/task_monitor/tasks/process_batches.rs

When for some reason (like tree rebuild or similar) tasks wait long for something, ticks are being buffered if time passes. It then results in multiple "ticks" same time when. When skip strategy is used then ticks are not buffered.

Skip ticks when missed.

---

src/identity/processor.rs

Fix finalization for offchain mode.

---

src/server/error.rs
src/server/mod.rs

Do not shutdown on request panic. Fix returned error format in body.

---

src/database/mod.rs
src/main.rs
src/task_monitor/mod.rs
tests/common/mod.rs

While tree is being initialized part of the endpoints return 5xx responses. To easily be able to not route traffic to such instance when running multiple in HA mode we can make tree intialization sync again. This way metrics server that is treated as healthcheck won't start before tree is initalized.

Make tree initialization sync process again.

---

src/database/methods.rs
src/ethereum/mod.rs
src/ethereum/write_provider/inner.rs
src/ethereum/write_provider/mod.rs
src/ethereum/write_provider/openzeppelin.rs
src/ethereum/write_provider/tx_sitter.rs
src/identity/processor.rs
src/identity_tree/initializer.rs
src/task_monitor/mod.rs
src/task_monitor/tasks/create_batches.rs
src/task_monitor/tasks/finalize_identities.rs
src/task_monitor/tasks/modify_tree.rs
src/task_monitor/tasks/monitor_txs.rs
src/task_monitor/tasks/process_batches.rs
src/task_monitor/tasks/sync_tree_state_with_db.rs
src/utils/mod.rs
tests/tree_restore_with_root_back_to_init.rs
tests/tree_restore_with_root_back_to_middle.rs

With multiple instances running same time it is possible that batches will be removed when they shouldn't (transaction not yet mined but scheduled and during that time instance starts).
We should not remove batches from database at all. Relayer should handle network reorgs by retrying already send transactions that were reverted.
Added small refactor with names for tasks to simplify debugging.

Remove batches correction. Add name for tasks for easier debugging.

---

crates/tx-sitter-client/src/data.rs
crates/tx-sitter-client/src/lib.rs
src/ethereum/write_provider/tx_sitter.rs

Some proxy services can respond with 409 status code which will lead to sequencer stucked.

Fix handling 409 tx-sitter response.
