.cargo/config.toml, Cargo.lock, Cargo.toml, src/cli/logging.rs, src/cli/main.rs, src/cli/prometheus.rs, src/cli/tokio_console.rs, src/poseidon_tree.rs
=> Add tokio-console support

.github/actions/setup-rust/action.yml, .github/workflows/build-test-deploy.yml, src/app.rs, src/lib.rs, tests/integration-tests.rs
Implement some of the advice from <https://matklad.github.io//2021/09/04/fast-rust-builds.html>
=> Smol tweaks

.github/actions/setup-rust/action.yml, .github/workflows/build-test-deploy.yml, Cargo.toml, Readme.md
=> Fix coverage

.dockerignore, .github/workflows/build-test-deploy.yml, Cargo.lock, Cargo.toml, Dockerfile, deploy/templates/ingress.yaml
=> Merge in updated template

.github/workflows/build-test-deploy.yml, .gitignore
Fix our deploy jobs
Use Github OIDC provider to authenticate to AWS
=> Deployment using Github OIDC provider [PRO-189]

.github/workflows/build-test-deploy.yml
=> Fix deploy

.github/workflows/build-test-deploy.yml, deploy/templates/deployment.yaml, deploy/values.yaml
- Deploying to prod cluster in prod AWS account
- Sneaking in update to Datadog host
- Removing secrets as container is now public
=> Deployment to prod cluster

.github/workflows/build-test-deploy.yml
=> set env for staging

src/ethereum/mod.rs
We're getting this error on trying to insert an identity
Add additional log entries to debug it
=> chore: Add more log entries once we use mock

.github/workflows/build-test-deploy.yml, deploy/templates/ebs-volumes.yaml, deploy/templates/headless-service.yaml, deploy/templates/statefulset.yaml, deploy/values.yaml
PR related to ticket: B-508
Change Deployment to Statefulset using statically provisioned AWS EBS Volume (separate for stage and prod)
=> Change Deployment to Statefulset with static volume

src/cli/logging.rs, src/server.rs
=> Add content-type header to response

.github/workflows/build-test-deploy.yml
=> set env vars

src/app.rs, src/server.rs
=> quick and dirty merkle root endpoint

src/app.rs
The initial leaf should be set to `0` to be compatible with the contracts.
=> set initial leaf to 0

src/app.rs, src/server.rs, tests/integration-tests.rs
This merges the two endpoints `getRoot` and `inclusionProof` into one, which resolves potential race conditions between calls.
=> merge getRoot and inclusionProof endpoint

.github/workflows/build-test-deploy.yml, deploy/templates/ebs-wipe.yaml
Requestor: Philipp
Risk: low
Description: We want to wipe attached volume in deployment pipeline on stage environment
=> feat: added wipe /volume step on stege deployment

src/ethereum/contract.rs, src/ethereum/mod.rs
- Fixes a bug in during syncing, in which roots were inserted instead of leaves (identityCommitments).
- Removes "checking" tx that tried to call `create_group` without a signer
=> fix event and remove tx check

.github/workflows/build-test-deploy.yml, deploy/templates/ebs-wipe.yaml, src/app.rs, src/ethereum/contract.rs, src/ethereum/mod.rs
=> Add flag to wipe storage on startup

src/app.rs, src/ethereum/mod.rs
=> compare roots for sanity check

.github/workflows/build-test-deploy.yml
The deployment stages failed due to timeouts. Increasing it from 60s to 120s to get rid of manual retries.
=> Increase helm upgrade timeout to 120s

src/app.rs, src/cli/logging.rs, src/ethereum/mod.rs, src/server.rs, tests/integration-tests.rs
- Removes mutex on whole `insertIdentity` endpoint
- Forces ordering of transaction through nonce calculation
- `create_group` into separate function
- Check only once if current address is manager at startup
=> Async transaction submission

.github/workflows/build-test-deploy.yml
This step made the [pipeline fail](https://github.com/worldcoin/signup-sequencer/runs/6285973655?check_suite_focus=true) and blocks deploying.
> kind cluster doesn’t support Persistent Volumes (in our case  its AWS EBS Volume), that’s why parameter persistentStorage.enabled=false - but in this case it could lead to some errors :confused: because we have no volumes connected to Statefulset
=> Remove helm test in pipeline for now

deploy/templates/base-auth-middleware.yaml, deploy/templates/ingress.yaml
Secure insertIdentity endpoint.
Adding Traefik auth middleware
=> Basic auth for insert identity

src/ethereum/mod.rs
=> Set gas limit also for legacy transactions

.github/workflows/build-test-deploy.yml
=> Increase helm timeout to 10min

.github/workflows/build-test-deploy.yml
=> Remove atomic timeout (for real)

.github/workflows/build-test-deploy.yml
=> decrease block range on prod

src/ethereum/mod.rs
=> fix event range sync

src/ethereum/mod.rs
=> panic on dropped tx

Cargo.lock, Cargo.toml, clippy.toml, src/app.rs, src/contracts/mod.rs, src/ethereum/mod.rs
=> Event streams

Cargo.lock, Cargo.toml, openapi.yaml, src/app.rs, src/ethereum/gas_oracle_logger.rs, src/ethereum/mod.rs, src/ethereum/rpc_logger.rs, src/server.rs, tests/integration-tests.rs
=> Fix issues, add loging and metering.

.github/workflows/build-test-deploy.yml
=> temporarily remove security audit

.github/workflows/build-test-deploy.yml, src/ethereum/mod.rs, tests/integration-tests.rs
=> Remove EIP1559 flag

src/app.rs, src/ethereum/min_gas_fees.rs, src/ethereum/mod.rs, src/lib.rs
=> Logging and min-max fees

.github/workflows/build-test-deploy.yml
=> set create_group_depth for staging

Cargo.lock, Cargo.toml, deploy/templates/statefulset.yaml, src/app.rs, src/contracts/mod.rs, src/ethereum/mod.rs, src/ethereum/transport.rs, src/lib.rs, src/server.rs, tests/integration-tests.rs
=> Update deps, add tracing

Cargo.lock, Cargo.toml
=> Fix tracing verbosity

Cargo.lock, Cargo.toml, deploy/templates/statefulset.yaml, src/app.rs, src/contracts/abi.rs, src/contracts/mod.rs, src/ethereum/mod.rs, src/ethereum/rpc_logger.rs, src/main.rs, src/server.rs, tests/integration-tests.rs
=> Add traces

Cargo.lock, Cargo.toml, clippy.toml, src/contracts/mod.rs, src/ethereum/mod.rs, src/ethereum/rpc_logger.rs, src/lib.rs
=> Fix logs / traces

.github/workflows/build-test-deploy.yml, Cargo.lock, Cargo.toml, deploy/templates/statefulset.yaml, src/server.rs
=> Otlp traces from requests and in logs

src/app.rs, src/server.rs
=> Pannicky timeouts

src/app.rs
=> increase timeout

.github/workflows/build-test-deploy.yml, src/app.rs, src/lib.rs, src/server.rs, src/timed_rw_lock.rs
=> Log verbosity + configurable lock timeout

.github/workflows/build-test-deploy.yml, Cargo.lock, Cargo.toml, src/ethereum/estimator.rs, src/ethereum/mod.rs
=> add PRIORITY_FEE_MULIPLIER

.github/workflows/build-test-deploy.yml, src/ethereum/min_gas_fees.rs, src/ethereum/mod.rs
=> new gas multiplier

.github/workflows/build-test-deploy.yml
=> temporarily disable tests in ci

.github/workflows/build-test-deploy.yml
=> Fetch 25k block logs

.github/workflows/build-test-deploy.yml, tests/integration-tests.rs
Fixes #247 
Also fixes redundant CLI argument
=> Fix integration test and deploy env args

.github/workflows/build-test-deploy.yml
=> Lower to 10k

.github/workflows/build-test-deploy.yml
=> Lower block range to 2k

Cargo.lock
=> update clap to 4.0.27

.github/workflows/build-test-deploy.yml
=> bump rust-cache

src/app.rs
Hiccups in service availability may render the internal state impossible to modify and cause crashes. Let's not lock the tree accross them.
=> Don't lock the tree accross network operations

deploy/main-stage.values.yaml, deploy/prod.values.yaml, deploy/stage-manual.values.yaml
=> Quote env values

.github/workflows/build-test-deploy.yml
=> Remove set line without key

schemas/database/005_store_parsed_logs.sql, src/app.rs, src/contracts/caching_log_query.rs, src/contracts/confirmed_log_query.rs, src/contracts/mod.rs, src/database.rs, src/ethereum/mod.rs, src/ethereum_subscriber.rs
Do as little as possible on startup. See results on my local machine, fully cached events.
=> experiment with faster startup times

src/app.rs, src/database/mod.rs, src/ethereum_subscriber.rs
=> check root before caching events, panic on mismatch

src/app.rs, src/database/mod.rs
=> Revert prod fix

.github/workflows/build-test-deploy.yml, Readme.md
=> remove --all-features from clippy

src/contracts/mod.rs, tests/integration_tests.rs
=> rename SEMAPHORE_ADDRESS to IDENTITY_MANAGER_ADDRESS again

deploy/templates/ingress.yaml
Fix annotations with middlewares names
=> fix: ingress for second deployment of signup-sequencer

src/identity_committer.rs
=> Fix incomplete batches

src/app.rs, src/server.rs
=> Backport the identity reduction check to `main`

schemas/database/002_create_root_history.sql, src/database/mod.rs
=> Fix root_history migration for psql

.github/workflows/build-test-deploy.yml, .github/workflows/phone-build-test-deploy.yml, Cargo.lock, Cargo.toml, Dockerfile, Readme.md, build.rs, deploy/Chart.yaml, deploy/batching-main-stage.values.yaml, deploy/phone-main-prod.values.yaml, deploy/phone-main-stage.values.yaml, deploy/templates/cors.yaml, deploy/templates/ingress.yaml, deploy/templates/statefulset.yaml, src/app.rs, src/contracts/batching/abi.rs, src/contracts/batching/mod.rs, src/contracts/legacy/abi.rs, src/contracts/legacy/mod.rs, src/contracts/mod.rs, src/ethereum_subscriber.rs, src/identity_committer.rs, src/lib.rs, src/prover/identity.rs, src/prover/mod.rs, src/prover/proof.rs, src/server.rs, tests/integration-tests.rs
Deployment for signup-sequencer-phone on stage env
=> feat: signup-sequencer-phone deployment on stage

.github/workflows/phone-build-test-deploy.yml
Deployment job for production environment.
=> feat: deployment for signup-sequencer-phone on prod env

src/app.rs, src/contracts/mod.rs, src/database/mod.rs
=> Fetch latest root from the smart contract & mark it as mined

src/database/mod.rs
=> Fix column names

src/app.rs, src/identity_tree.rs
=> Keep every root

deploy/templates/ingress.yaml
Expose the new endpoint in deployment config
=> Expose verify semaphore proof endpoint in charts

.github/workflows/batching-build-test-deploy.yml, .github/workflows/build-test-deploy.yml
=> Fixing and improving caching in Github Actions workflow for batching

Cargo.toml
=> Switch to tree size = 30

src/task_monitor.rs, src/task_monitor/tasks/insert_identities.rs, src/task_monitor/tasks/process_identities.rs
Replaces the wake up channel with a `Notify`. So that we are not limited to the number of identities inserted as pending into the database.
=> Replace wake up sender channel with notify

src/task_monitor/tasks/process_identities.rs
=> Also wake up on tick

deploy/batching-main-stage.values.yaml
=> Update contract address

src/database/mod.rs
=> mark_root_as_mined should invalidate the roots following as pending

src/identity_tree.rs, src/task_monitor.rs, src/task_monitor/tasks/mine_identities.rs, src/task_monitor/tasks/process_identities.rs
=> Update the tree based on root

src/app.rs
=> Log tree initialization time

Cargo.lock, Cargo.toml
=> Use updated cli-batteries

src/ethereum/write_oz/mod.rs
=> Remove default OZ address

schemas/openapi.yaml
=> Remove groupId mention

schemas/openapi.yaml, src/app.rs
=> Status code 202 accepted for pending identity

src/ethereum/write_oz/mod.rs, src/ethereum/write_oz/openzeppelin.rs
=> Add configurable OZ timeouts

.github/workflows/update-deployment.yaml
This workflow will create PR to bump up the version in the external repository.
=> feat: update deployment workflow

.github/workflows/test.yml, tests/common/chain_mock.rs, tests/insert_identity_and_proofs.rs
=> Add test workflow

src/ethereum/write_oz/mod.rs, src/ethereum/write_oz/openzeppelin.rs
=> Allow overriding gas limit

schemas/database/002_batch_sizes.sql, src/app.rs, src/contracts/mod.rs, src/database/mod.rs, src/database/prover.rs, src/prover/batch_insertion/mod.rs, src/prover/map.rs, src/server/error.rs
This PR is a follow up to #485
=> support for dynamic batch sizes at runtime

src/server.rs
=> Customize axum tracing

Cargo.lock, Cargo.toml, src/task_monitor/tasks/insert_identities.rs, src/task_monitor/tasks/mine_identities.rs, src/task_monitor/tasks/process_identities.rs
=> DataDog tracing

src/database/mod.rs, src/lib.rs, src/secret.rs, src/server/mod.rs, src/server/remove_auth_layer.rs
Restored branch for PR 515, to be merged into main
=> removing sensitive info from logs

src/server/mod.rs, tests/common/mod.rs
=> Bring back status codes

src/database/mod.rs
=> Fix checking if identity exists

Cargo.lock, Cargo.toml, src/server/custom_middleware.rs, src/server/custom_middleware/logging_layer.rs, src/server/mod.rs, tests/malformed_payload.rs
Also parses the body and ensures the body doesn't exceed allowed size (to safeguard against malicious requests)
=> Custom request logging layer

src/server/custom_middleware/logging_layer.rs, src/server/mod.rs
=> Add spans to requests

tests/dynamic_batch_sizes.rs, tests/insert_identity_and_proofs.rs, tests/more_identities_than_dense_prefix.rs
=> Dzejkop test restore

src/database/mod.rs
=> Limit unprocessed identities fetch

Cargo.lock, Cargo.toml, schemas/database/004_change_mined_to_finalized.sql, src/app.rs, src/contracts/abi.rs, src/contracts/mod.rs, src/database/mod.rs, src/ethereum/mod.rs, src/ethereum/read/mod.rs, src/ethereum/write_oz/mod.rs, src/identity_tree.rs, src/lib.rs, src/prover/batch_insertion/mod.rs, src/serde_utils.rs, src/task_monitor.rs, src/task_monitor/tasks/finalize_identities.rs, src/task_monitor/tasks/mine_identities.rs, src/task_monitor/tasks/mod.rs, tests/common/mod.rs, tests/dynamic_batch_sizes.rs, tests/insert_identity_and_proofs.rs, tests/malformed_payload.rs, tests/multi_prover.rs, tests/unavailable_prover.rs, tests/validate_proofs.rs
=> Make sequencer multi-chain : Adds "finalized" status

schemas/database/004_change_mined_to_finalized.sql, src/app.rs, src/database/mod.rs, src/identity_tree.rs, src/task_monitor.rs, src/task_monitor/tasks/finalize_identities.rs, src/task_monitor/tasks/mine_identities.rs, tests/common/mod.rs
=> Change flow to pending -> processed -> mined, instead of pending -> mined -> finalized

src/task_monitor/tasks/mine_identities.rs, src/task_monitor/tasks/process_identities.rs
=> Panic on unsucessful mininig

src/task_monitor/tasks/mine_identities.rs
=> Remove panic

tests/common/mod.rs
=> Stabilize tests

src/app.rs, src/server/custom_middleware/logging_layer.rs
=> Dzejkop/Some API and logging changes

src/database/mod.rs
=> Optimize update_previous_roots query

src/task_monitor.rs, src/task_monitor/tasks/finalize_identities.rs
=> Allow overriding finalization times with env vars

schemas/openapi.yaml, src/app.rs, src/server/error.rs, src/server/mod.rs, tests/common/mod.rs, tests/validate_proof_with_age.rs
=> Add option to validate semaphore proof with root age

tests/common/mod.rs, tests/common/prover_mock.rs, tests/delete_padded_identity.rs
Adds padded deletion tests
`tests/delete_identity_padded.rs`
=> add padded deletion tests

src/database/mod.rs, src/identity_tree.rs, src/task_monitor/tasks/finalize_identities.rs, src/task_monitor/tasks/process_identities.rs
=> Minor fixes

Dockerfile
=> Update debian to 12

src/app.rs, src/database/mod.rs, src/utils.rs, src/utils/tree_updates.rs
=> Fix get commitments by status

schemas/openapi.yaml
This PR adds the API schema for new endpoints related to deletion and recovery.
=> API Schema for deletion / recovery endpoints

src/server/error.rs
=> Change status code on duplicate deletion to 409

LICENSE.md
updates licensee to Worldcoin Foundation
=> update license to Worldcoin Foundation

schemas/openapi.yaml
This PR fixes the API schema for the `recoverIdentity` endpoint.
=> fix: recovery request api schema

src/task_monitor.rs, src/task_monitor/tasks/finalize_identities.rs
=> Add max epoch duration

Cargo.lock, Cargo.toml, src/app.rs, src/database/mod.rs, src/identity_tree.rs, supply-chain/config.toml, supply-chain/imports.lock, tests/delete_identities.rs, tests/delete_padded_identity.rs, tests/dynamic_batch_sizes.rs, tests/insert_identity_and_proofs.rs, tests/malformed_payload.rs, tests/more_identities_than_dense_prefix.rs, tests/multi_prover.rs, tests/recover_identities.rs, tests/unavailable_prover.rs, tests/unreduced_identity.rs, tests/validate_proof_with_age.rs, tests/validate_proofs.rs
Rebasing older branch was too troublesome, so i made a new one
=> tree mmap cache

Readme.md, src/app.rs, src/database/mod.rs, src/database/types.rs, src/identity_tree.rs, src/identity_tree/status.rs, src/task_monitor/tasks/insert_identities.rs, tests/common/mod.rs, tests/recover_identities.rs
=> Audit-changes

src/app.rs
=> Allow forcing cache purge

src/app.rs, src/database/mod.rs
=> Empty root exception & purge cache if necessary.

schemas/database/011_drop_root_uniqueness.sql, src/app.rs, src/contracts/abi.rs, src/database/mod.rs, src/identity_tree/status.rs, src/lib.rs, src/main.rs, src/server/data.rs, src/task_monitor/tasks/delete_identities.rs, src/task_monitor/tasks/finalize_identities.rs, src/task_monitor/tasks/insert_identities.rs, src/task_monitor/tasks/monitor_txs.rs, src/utils/index_packing.rs, src/utils/tree_updates.rs, tests/common/mod.rs, tests/delete_identities.rs, tests/delete_padded_identity.rs, tests/dynamic_batch_sizes.rs, tests/identity_history.rs, tests/recover_identities.rs
=> Drop the uniqueness constraint

Readme.md, src/contracts/abi.rs
Hello,
I fixed some typos found in your documentation
Hope it helps.
Best regards,Elias.
=> Fix several typos

.github/workflows/test.yml, Cargo.lock, Cargo.toml, crates/cognitoauth/Cargo.toml, crates/cognitoauth/README.md, crates/cognitoauth/src/cognito_srp_auth.rs, crates/cognitoauth/src/error.rs, crates/cognitoauth/src/lib.rs, crates/oz-api/Cargo.toml, supply-chain/config.toml, supply-chain/imports.lock
=> Remove vulnerable webpki dependency

.github/workflows/build-image-and-publish.yml
=> Publish docker images in CI

src/database/mod.rs, src/prover/mod.rs
=> Fix invalid deduplication logic

schemas/database/012_add_missing_indexes.sql
=> Add missing index

src/app.rs, src/database/mod.rs
=> Fix deletion reordering

src/server.rs, tests/common/mod.rs
Creates a health check route which just returns 200 OK.
=> Health Check

.github/workflows/audit.yml, .github/workflows/test.yml, Cargo.lock, rust-toolchain.toml, src/app.rs, src/database/mod.rs, src/database/types.rs, src/identity_tree.rs, src/identity_tree/status.rs, src/lib.rs, src/main.rs, src/prover.rs, src/task_monitor.rs, src/task_monitor/tasks/delete_identities.rs, src/task_monitor/tasks/finalize_identities.rs, src/task_monitor/tasks/insert_identities.rs, src/task_monitor/tasks/process_identities.rs, supply-chain/config.toml, tests/common/mod.rs
DB refactor to make queries more composable. Diff looks big but it's mostly just shuffling. This depends on branch `ewoolsey/update-sqlx`
=> db query refactor for composability PRO-535

.github/workflows/test.yml, supply-chain/config.toml, supply-chain/imports.lock
=> Update vetted entries

.github/workflows/test.yml, Cargo.lock, Cargo.toml, Dockerfile, build.rs, src/config.rs, src/lib.rs, src/main.rs, src/server.rs, src/server/custom_middleware/logging_layer.rs, src/shutdown.rs, src/utils.rs, supply-chain/config.toml, supply-chain/imports.lock, tests/common/mod.rs, tests/common/test_config.rs
Migrate signup sequencer to `telemetry-batteries` from `cli-batteries`
=> Telemetry Batteries PRO-536

src/config.rs, src/main.rs, src/server.rs, tests/common/mod.rs
Removed dependence on metrics from `telemetry-batteries`
=> Prometheus Endpoint

src/task_monitor.rs, src/task_monitor/tasks/delete_identities.rs, src/task_monitor/tasks/insert_identities.rs, src/task_monitor/tasks/process_identities.rs
This PR applies the hotfixes contained in [1.0.3](https://github.com/worldcoin/signup-sequencer/releases/tag/1.0.3) - [1.0.5](https://github.com/worldcoin/signup-sequencer/releases/tag/1.0.5), updating the following logic:
- Introduces `pending_insertions_mutex` to ensure that deletion and insertion updates are not interleaved into the `pending_identities` table.
- Updates `process_identities` task to process deletions immediately and process partial insertion batches when the next batch is deletion.
=> fix(deletions): Deletions hotfix

Cargo.lock, Cargo.toml, src/main.rs
=> Bump telemetry batteries

Readme.md
TX sitter is not mentioned in the documentation.
Add tx-sitter fetch&build step.
=> doc: add tx-sitter as build depencency

Readme.md
Missing default config file for signup-sequencer
Add an example of config file.
=> doc: add signup-sequencer default config

crates/tx-sitter-client/src/lib.rs
=> Fix tx-sitter backwards incompatibility

src/ethereum/write/mod.rs
=> Full print anyhow error

Cargo.lock, Cargo.toml
=> Bump telemetry-batteries

src/app.rs, src/identity_tree/initializer.rs, src/identity_tree/mod.rs, src/task_monitor/tasks/create_batches.rs, src/task_monitor/tasks/delete_identities.rs, src/task_monitor/tasks/insert_identities.rs, tests/common/mod.rs
Previously some group of operations were only `read` ones. This change is restoring that state (and naming). Update operation is being moved to only latest tree as only latest tree could be modified freely. Other trees are done by applying only same operations as to trees previous in chain.
=> Allow only to update latest tree.

schemas/database/017_comittment_uniqueness_for_identities.down.sql, schemas/database/017_comittment_uniqueness_for_identities.up.sql
=> Add unique index for commitments to identities.

e2e_tests/scenarios/tests/common/api.rs, e2e_tests/scenarios/tests/common/mod.rs, src/app.rs, src/bin/tool.rs, src/database/methods.rs, src/identity/processor.rs, src/identity_tree/initializer.rs, src/identity_tree/mod.rs, src/identity_tree/status.rs, src/server/data.rs, src/task_monitor/tasks/delete_identities.rs, src/task_monitor/tasks/finalize_identities.rs, tests/common/mod.rs, tests/insert_identity_and_proofs.rs
We need to revert status field as it is used by apps. Some changes also brings back original app behaviour and responses.
=> Restore status for identities. Fix tests.

src/identity/processor.rs, src/identity_tree/initializer.rs
Fixing how tree is being restored.
=> Fix tree restore on startup.

src/identity_tree/initializer.rs
=> Fix restoring tree from cache with mined status back.

schemas/database/018_status_index_for_identities.down.sql, schemas/database/018_status_index_for_identities.up.sql
=> Add index on status column in identities table.

schemas/database/016_remove_recovery.down.sql, schemas/database/016_remove_recovery.up.sql
=> Fix migration.

Dockerfile
=> Improve dockerfile caching chance.

schemas/database/016_remove_recovery.down.sql
=> Fix down migration 16.

e2e_tests/docker-compose-offchain/compose.yml, e2e_tests/docker-compose-offchain/haproxy/haproxy.cfg, e2e_tests/docker-compose/compose.yml, e2e_tests/docker-compose/haproxy/haproxy.cfg, e2e_tests/scenarios/tests/common/docker_compose.rs
=> Fix multiple instances config.

src/lib.rs, src/monitoring/mod.rs, src/task_monitor/mod.rs, src/task_monitor/tasks/create_batches.rs, src/task_monitor/tasks/monitor_queue.rs
=> Improve monitoring.

Cargo.lock, Cargo.toml, src/app.rs, src/server/data.rs, src/server/mod.rs, supply-chain/config.toml
Add handling of compressed proofs in the API
=> Support proof compression

src/app.rs, src/database/methods.rs, src/identity_tree/mod.rs, src/identity_tree/state.rs
=> Fix returning inclusion proofs on not synced instances.

src/identity_tree/initializer.rs
With multiple instances running we run into race condition where latest batch in database was ahead of what was restored. It was seen during the load on the service. This changes how the tree is being initialized reusing sync method.
=> Change how tree is intialized.

schemas/openapi-v2.yaml
We want to remove some fields in the API without breaking old customers flow. It is also opportunity to put into API what we learned so far from users.
Link to Swagger UI rendering spec [here](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/worldcoin/signup-sequencer/refs/heads/piohei/api_v2/schemas/openapi-v2.yaml)
=> API v2 spec proposal

e2e_tests/scenarios/tests/common/docker_compose.rs, schemas/database/022_add_columns_for_metrics.down.sql, schemas/database/022_add_columns_for_metrics.up.sql, src/app.rs, src/database/methods.rs, src/database/mod.rs, src/database/types.rs, src/identity_tree/db_sync.rs, src/identity_tree/initializer.rs, src/task_monitor/tasks/modify_tree.rs, src/task_monitor/tasks/sync_tree_state_with_db.rs, tests/common/mod.rs
New columns are needed to track how much time we need to include identity in the tree.
=> Refactor database methods. Add new columns for metrics purposes.

src/database/methods.rs, src/identity_tree/builder.rs, src/identity_tree/db_sync.rs, src/identity_tree/initializer.rs, src/identity_tree/mod.rs, src/task_monitor/tasks/sync_tree_state_with_db.rs, src/utils/tree_updates.rs
=> Add log with processing time to add to latest tree.

.github/workflows/test.yml, Cargo.lock, Cargo.toml, rust-toolchain.toml
Fixes recent issue we've been seeing with invalid semaphore proofs.
=> Verify Proof Panic Fix

schemas/openapi-v2.yaml
Adds 410 gone status to the identity endpoints when an identity has been deleted.
=> update schema v2 with 410 gone

schemas/openapi-v2.yaml
Few changes to return more information from API.
=> Update API v2 schema.

schemas/openapi-v2.yaml, src/server/api_v2/mod.rs
Make it easier to pass commonly used field format.
- [ X ] Added Tests
- [ X ] Added Documentation
=> Allow not zero padded commitments in API v2.

e2e_tests/docker-compose-offchain/compose.yml, e2e_tests/docker-compose/compose.yml, src/app/mod.rs, src/identity_tree/db_sync.rs, src/identity_tree/initializer.rs, src/server/api_v2/mod.rs, src/task_monitor/tasks/create_batches.rs, src/task_monitor/tasks/modify_tree.rs, src/task_monitor/tasks/sync_tree_state_with_db.rs, tests/common/mod.rs, tests/tree_restore_empty.rs, tests/tree_restore_multiple_commitments.rs, tests/tree_restore_one_commitment.rs
=> Add mutex guard around tree state.
